apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  labels:
    {{- include "chart.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  name: {{ include "chart.serviceAccountName" . }}
