apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- .Values.service.ports | toYaml | nindent 4 }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
