apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: api-service
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: api-service
  spec:
    selector:
      app: api
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
