apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: build-java-component
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${COMPONENT}
    name: ${COMPONENT}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${COMPONENT}
    name: ${COMPONENT}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${COMPONENT}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${SOURCE_CODE_REF}
        uri: ${SOURCE_CODE_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: ARTIFACT_DIR
          value: ${COMPONENT}/target
        - name: ARTIFACT_COPY_ARGS
          value: -r ${JAR_NAME}${JAR_VERSION}.jar
        - name: MAVEN_ARGS
          value: -e -Prelease -DskipTests -Dfabric8.skip=true package
        - name: MAVEN_ARGS_APPEND
          value: -pl ${COMPONENT} -am
        from:
          kind: ImageStreamTag
          name: java:latest
          namespace: openshift
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 019d3db99764e75e
      type: Generic
    - github:
        secret: dca9639337f3d252
      type: GitHub
  status:
    lastVersion: 0
parameters:
  - name: COMPONENT
  - name: JAR_NAME
  - name: JAR_VERSION
  - name: SOURCE_CODE_URL
    value: https://github.com/Hygieia/Hygieia.git
  - name: SOURCE_CODE_REF
    value: v3.0.1
