apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: hygieia-jenkins-build-collector
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: hygieia-jenkins-build-collector
    name: hygieia-jenkins-build-collector
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: hygieia-jenkins-build-collector
    name: hygieia-jenkins-build-collector
  spec:
    runPolicy: Serial 
    triggers: 
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
    - type: ImageChange
    source: 
      git:
        uri: https://github.com/tomgeorge/Hygieia
        ref: jenkins-oauth-support
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: ARTIFACT_DIR
          value: collectors/build/jenkins/target
        - name: ARTIFACT_COPY_ARGS
          value: -r jenkins-build-collector-3.0.1.jar
        - name: MAVEN_ARGS
          value: -e -P release -DskipTests -Dfabric8.skip=true package
        - name: MAVEN_ARGS_APPEND
          value: -pl collectors/build/jenkins -am
        from:
          kind: ImageStreamTag
          name: java:8
          namespace: openshift
      type: Source
    output: 
      to:
        kind: ImageStreamTag
        name: hygieia-jenkins-build-collector:latest
