apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq_conf
data: 
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.address_type = hostname
