---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: project-template
metadata:
  name: project-template
objects:
- apiVersion: project.openshift.io/v1
  kind: ProjectRequest
  metadata:
    name: ${NAMESPACE}
    creationTimestamp: null
  displayName: ${DISPLAY_NAME}
parameters:
- name: NAMESPACE
- name: DISPLAY_NAME
