apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ubi-minimal
  spec:
    dockerImageRepository: registry.access.redhat.com/ubi8/ubi-minimal
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/ubi-minimal:8.3
      importPolicy: {}
      name: "8.3"
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/ubi-minimal:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
