#!/bin/bash


USER_ID=$(id -u)
GROUP_ID=$(id -g)

# Check if user already exists
ADD_USER=$(grep $USER_ID /etc/passwd | wc -l)

if [ $ADD_USER -eq 0 ];then
  echo "User $USER_ID does not exists. Adding the user to /etc/passwd..."
  if [ x"$USER_ID" != x"0" -a x"$USER_ID" != x"997" ]; then
    echo "tool-box:x:${USER_ID}:${GROUP_ID}:Tool Box User:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
else
  echo "User $USER_ID already exists"
fi


if [ -v RUN_AS_WEBSERVER ]; then
    hoverctl start webserver
else
    hoverctl start
fi    

hoverctl logs --follow