#!/bin/sh

SOURCE_DIR=/tmp/src

if [ ! -d "$SOURCE_DIR" ]; then
   echo "Error: Source volume not mounted or available"
   exit 1
fi

cd "$SOURCE_DIR"

bundle install
bundle exec jekyll build

chmod -R g+rwX $SOURCE_DIR
