---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Python Kopf Operator Framework
  name: python-kopf
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: |-
        Build and run operators with Python Kopf 1.37.
        https://kopf.readthedocs.io/
      iconClass: icon-python
      openshift.io/display-name: Python Kopf
      sampleRepo: https://github.com/redhat-cop/build-s2i-python-kopf/example.git
      supports: kopf:1.37,kopf,python:3.8,python
      tags: builder,python,kopf
      version: "1.37"
    from:
      kind: DockerImage
      name: quay.io/redhat-cop/python-kopf-s2i:v1.37
    importPolicy: {}
    name: "1.37"
    referencePolicy:
      type: Local
  - annotations:
      description: |-
        Build and run operators with Python kopf.
        https://kopf.readthedocs.io/

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Python Kopf available, including major version updates.
      iconClass: icon-python
      openshift.io/display-name: Python Kopf
      sampleRepo: https://github.com/redhat-cop/build-s2i-python-kopf/example.git
      supports: kopf,python
      tags: builder,python,kopf
    from:
      kind: DockerImage
      name: quay.io/redhat-cop/python-kopf-s2i:latest
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
