= Python Kopf Operator Source-to-Image (s2i)

Source-to-Image for python https://kopf.readthedocs.io/en/latest/[kopf] based operators.

== Usage

TBD

=== Building a Python Kopf Operator

TBD

=== Kopf Options

Kopf command line options are configured using environment variables.
The file `kopf-opt.sh` may be used to set options at compile time.
These are used to build up the command line for `kopf run`.
The following environment variables are supported:

[options="header",cols="2,1,6"]
|=======================
|Option
|Default
|Description

|`KOPF_NAMESPACED`
|`false`
|Set to "true" to run kopf with `--namespace` option to restrict watch to specific namespace.

|`KOPF_NAMESPACE`
|none
|Namespace for kopf watch.
When run in cluster this defaults to the operator pod namespace.

|`KOPF_STANDALONE`
|`false`
|Set to "true" to run kopf with `--standalone` option.
This prevents kopf from peering and talking to other kopf operators.

|`KOPF_PRIORITY`
|dynamic
|Operator priority in relation to other kopf operators.
The default when running containerized is to base the priority on the pod IP or otherwise `${RANDOM}` if the IP address cannot be determined.

|`KOPF_PEERING`
|none
|Kopf custom peering using `--peering` option.

|`KOPF_OPTIONS`
|none
|Command line options for `kopf run` to support features not covered by other configuration variables.
|=======================

=== Python Requirements

Python requirements can be specified in the `requirements.txt` file.
These will be processed and installed to the container image during source-to-image build using Python3 `pip`.

=== Deploying

Liveness probe on TCP port 8080.

== Development

TBD

=== Building this Source-to-Image Base Image

==== OpenShift

An OpenShift build template is provided for building this container image.

Create events console build configuration:

------------------------------------------------------------
oc process --local -f build-template.yaml | oc apply -f -
------------------------------------------------------------

Then either build the python-kopf-s2i image from git source:

------------------------------------------------------------
oc start-build python-kopf-s2i
------------------------------------------------------------

Or build the python-kopf-s2i image from local source:

------------------------------------------------------------
oc start-build python-kopf-s2i --from-dir=../ -F
------------------------------------------------------------

==== Dockerfile

This image may also be built with the provided `Dockerfile`.

Using `podman`:

--------------------------------------------------------------
sudo podman build --tag python-kopf-s2i:latest -f ./Dockerfile
--------------------------------------------------------------

Using `docker`:

---------------------------------------------
sudo docker build -t python-kopf-s2i:latest .
---------------------------------------------

=== Testing s2i build with the Provided Example

To verify the source-to-image base image is functional you will want to build an operator image to verify functionality.
A simple operator example is provided in the `example/` directory.

==== OpenShift

If testing the source-to-image build in an OpenShift cluster then you may use the example build template provided:

Create events console build configuration:

--------------------------------------------------------------------------------
oc process --local -f example/build-template.yaml \
-p FROM_IMAGE=$(oc get is python-kopf-s2i -o jsonpath="{.status.tags[?(@.tag=='latest')].items[0].dockerImageReference}") \
| oc apply -f -
--------------------------------------------------------------------------------

Then either build the example operator from git source:

------------------------------------------------------------
oc start-build python-kopf-s2i-example
------------------------------------------------------------

Or build the example from local source:

------------------------------------------------------------
oc start-build python-kopf-s2i-example --from-dir=../ -F
------------------------------------------------------------

Testing in OpenShift

--------------------------------------------------------------------------------
oc process --local -f example/deploy-template.yaml \
-p IMAGE=$(oc get is python-kopf-s2i-example -o jsonpath="{.status.tags[?(@.tag=='latest')].items[0].dockerImageReference}") \
| oc apply -f -
--------------------------------------------------------------------------------

==== Dockerfile

This example image may also be built with the provided `Dockerfile`.
The provided configuration builds from the base image `quay.io/redhat-cop/python-kopf-s2i:latest`.
In order to test your build of the s2i image you will need a modified version of the `Dockerfile`:

--------------------------------------------------------------------------------
sed 's/^FROM .*/FROM python-kopf-s2i:latest/' example/Dockerfile >example/Dockerfile.custom
--------------------------------------------------------------------------------

Build using `podman`:

--------------------------------------------------------------------------------
sudo podman build --tag python-kopf-s2i-example:latest -f ./example/Dockerfile.custom
--------------------------------------------------------------------------------

Using `docker`:

--------------------------------------------------------------------------------
sudo docker build -t python-kopf-s2i-example:latest -f ./example/Dockerfile.custom example/
--------------------------------------------------------------------------------
