# This is the Ansible Galaxy requirements file to pull in the correct roles
# to support the operation of CASL provisioning/runs. 

# From 'casl-ansible'
- src: https://github.com/redhat-cop/casl-ansible
  scm: git
  version: v3.6.2
  name: casl-ansible
