---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}"
  annotations:
    openshift.io/display-name: Generic Dockerfile Build
objects:
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      build: "${NAME}"
      template: docker-build-template-binary-with-push-secret
    name: "${NAME}"
  spec:
    failedBuildsHistoryLimit: 5
    output:
      pushSecret:
        name: "${PUSH_SECRET}"
      to:
        kind: DockerImage
        name: "${DESTINATION_REPO_NAME}/${DESTINATION_REPO_NAMESPACE}/${DESTINATION_IMAGE_NAME}:${DESTINATION_IMAGE_TAG}"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy:
        dockerfilePath: "${DOCKERFILE_NAME}"
        from:
          kind: DockerImage
          name: "${BUILDER_IMAGE_NAME}"
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers: []
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects.
  required: true
- name: PUSH_SECRET
  displayName: Push Secret
  description: The name of the secret that contains the authentication information for the docker repository you are pushing the docker image to.
  required: true
- name: DESTINATION_IMAGE_NAME
  displayName: Destination Docker Image Name
  description: The name of the image to be uploaded to the docker repository.
  required: true
- name: DESTINATION_REPO_NAME
  displayName: Destination Docker Repo Name
  description: The name of the repo the docker image will be uploaded to.
  required: true
- name: DESTINATION_IMAGE_TAG
  displayName: Destination Docker Image Tag
  description: The tag of the image to be uploaded to the docker repository.
  required: true
- name: DESTINATION_REPO_NAMESPACE
  displayName: Destination Repository Namespace
  description: The repository namespace that the image will be uploaded to.
  required: true
- name: DOCKERFILE_NAME
  displayName: Docker file path.
  description: Docker file path.
  required: true
  value: Dockerfile
- name: BUILDER_IMAGE_NAME
  displayName: Image name from which to build this pod
  description: The build image which this build pod will extend to create it's new build pod type.
  required: true
