---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}"
  annotations:
    openshift.io/display-name: Generic Dockerfile Build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "${NAME}"
      app: "${NAME}"
    name: "${NAME}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "${NAME}"
      app: "${NAME}"
      type: "image"
    name: "${NAME}"
  spec:
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: "${SOURCE_CONTEXT_DIR}"
      git:
        ref: "${SOURCE_REPOSITORY_REF}"
        uri: "${SOURCE_REPOSITORY_URL}"
      type: Git
      sourceSecret:
        name: "${SOURCE_REPOSITORY_SECRET}"
    strategy:
      type: Docker
    triggers:
    - type: GitHub
      github:
        secret: "${WEBHOOK_SECRET}"
    - type: GitLab
      gitlab:
        secret: "${WEBHOOK_SECRET}"
    - type: BitBucket
      gitlab:
        secret: "${WEBHOOK_SECRET}"
    - type: Generic
      generic:
        secret: "${WEBHOOK_SECRET}"
        allowEnv: true
    - type: ConfigChange
    - type: ImageChange
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
- name: WEBHOOK_SECRET
  displayName: Webhook Secret
  description: A secret string used to configure the webhook.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your Dockerfile
  required: true
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default (master) branch.
  value: master
- name: SOURCE_CONTEXT_DIR
  displayName: Git Context Directory
  description: Set this to the directory where the build information is (e.g. Dockerfile)
    if not using the root directory
- name: SOURCE_REPOSITORY_SECRET
  displayName: Secret for git repository
  description: The name of the OCP secret that has credentials for the pipeline git
    repository
  value: ''