apiVersion: v1
kind: Template
labels:
  template: s2i-gows
metadata:
  annotations:
    description: GoWS Deployment and Runtime Components
    iconClass: icon-go
    tags: go,s2i
  name: "${APPLICATION_NAME}"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    replicas: 1
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
          deploymentconfig: "${APPLICATION_NAME}"
      spec:
        containers:
        - image: "${APPLICATION_NAME}:latest"
          name: "${APPLICATION_NAME}"
          ports:
          - containerPort: ${{APPLICATION_PORT}}
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APPLICATION_NAME}:latest"
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: "${APPLICATION_PORT}-tcp"
      port: ${{APPLICATION_PORT}}
      protocol: TCP
      targetPort: ${{APPLICATION_PORT}}
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    port:
      targetPort: "${APPLICATION_PORT}-tcp"
    to:
      kind: ""
      name: "${APPLICATION_NAME}"
      weight: null
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: gows
- description: The port for the application.
  name: APPLICATION_PORT
  required: true
  value: "8080"
