apiVersion: v1
kind: Template
labels:
  template: rabbitmq
metadata:
  annotations:
    description: RabbitMQ Deployment and Runtime Components
    iconClass: icon-erlang
    tags: erlang,rabbitmq
  name: rabbitmq
objects:
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      application: "${APPLICATION_NAME}"
    name: view
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: default
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    clusterIP: None
    ports:
    - name: 4369-tcp
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: 5671-tcp
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: 5672-tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: 25672-tcp
      port: 25672
      protocol: TCP
      targetPort: 25672
    selector:
      application: "${APPLICATION_NAME}"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    labels:
      application: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    replicas: 3
    selector:
      matchLabels:
        application: "${APPLICATION_NAME}"
    serviceName: "${APPLICATION_NAME}"
    template:
      metadata:
        labels:
          application: "${APPLICATION_NAME}"
      spec:
        containers:
        - env:
          - name: AUTOCLUSTER_DELAY
            value: "10"
          - name: AUTOCLUSTER_TYPE
            value: k8s
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: RABBITMQ_ERLANG_COOKIE
            value: sup3rS3cr1+
          - name: RABBITMQ_NODENAME
            value: rabbit@$(MY_POD_IP)
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          image: "${APPLICATION_NAME}:${RABBITMQ_VERSION}"
          imagePullPolicy: Always
          name: "${APPLICATION_NAME}"
          ports:
          - containerPort: 25672
            protocol: TCP
          - containerPort: 4369
            protocol: TCP
          - containerPort: 5671
            protocol: TCP
          - containerPort: 5672
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: mnesia
            mountPath: /var/lib/rabbitmq/mnesia
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 10
    volumeClaimTemplates:
    - metadata:
        name: mnesia
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: rabbitmq
- description: RabbitMQ version to build
  name: RABBITMQ_VERSION
  required: true
  value: 3.6.12
