#!/bin/bash
IMAGE_NAMESPACE=openshift

deploy() {
  app_name=${1}
  deploy_templates=${2:-1}

  # Ensure image builds project exists
  create_project ${IMAGE_NAMESPACE}

  echo "Creating a pipeline for ${app_name} application..."
  if [ ${deploy_templates} -eq 1 ]; then
    apply_template jenkins-slaves/templates/jenkins-slave-image-mgmt-template.json
    apply_template cicd/jenkins-s2i/jenkins-s2i.yml \
      -v JENKINS_GIT_URL=https://github.com/redhat-cop/containers-quickstarts.git \
      -v JENKINS_GIT_CONTEXT_DIR=cicd/jenkins-s2i
    create_template cicd/pipeline-basic/generic-java-jenkins-pipeline.yml
    create_template cicd/pipeline-basic/jws30-tomcat8-deployment.yml
  else
    echo "skipping template deployment"
  fi

  # Create Projects
  create_project ${app_name}-dev
  create_project ${app_name}-stage
  create_project ${app_name}-prod

  # Configure serviceaccount
  oc policy add-role-to-user edit system:serviceaccount:${app_name}-dev:jenkins -n ${app_name}-stage
  oc policy add-role-to-user edit system:serviceaccount:${app_name}-dev:jenkins -n ${app_name}-prod

  # Create jenkins master
  oc process openshift//jenkins-ephemeral JENKINS_IMAGE_STREAM_TAG=jenkins2-s2i:latest NAMESPACE=${IMAGE_NAMESPACE} | oc apply -f - -n ${app_name}-dev

  # Create application deployments
  oc process ${IMAGE_NAMESPACE}//jws30-tomcat8-deployment APPLICATION_NAME=${app_name} | oc apply -f - -n ${app_name}-dev
  oc process ${IMAGE_NAMESPACE}//jws30-tomcat8-deployment APPLICATION_NAME=${app_name} | oc apply -f - -n ${app_name}-stage
  oc process ${IMAGE_NAMESPACE}//jws30-tomcat8-deployment APPLICATION_NAME=${app_name} | oc apply -f - -n ${app_name}-prod

  # Instantiate pipeline
  oc process ${IMAGE_NAMESPACE}//generic-java-jenkins-pipeline APPLICATION_NAME=${app_name} | oc apply -f - -n ${app_name}-dev

  echo "Done!"

}

apply_template() {
  # For each of our templates we're going to first, attempt to create it, and if that fails, we'll replace it
  template=${1}
  shift
  args=${@}
  oc process -f ${template} ${args} \
    | oc apply -f- -n ${IMAGE_NAMESPACE}
}

create_template() {
  # For each of our templates we're going to first, attempt to create it, and if that fails, we'll replace it
  template=${1}
  shift
  args=${@}
  oc apply -f ${template} -n ${IMAGE_NAMESPACE}
}

create_project() {
  oc new-project ${1} --skip-config-write=true 2>/dev/null
}

cleanup() {
  app_name=${1}

  oc delete projects ${app_name}-dev ${app_name}-stage ${app_name}-prod
}

if [ "$(basename $PWD)" != "containers-quickstarts" ]; then
  echo "You must be in the 'containers-quickstarts' directory to run this script."
  exit 1
fi

method=${1}
shift
app_name=${1}
shift


while [[ $# -gt 1 ]]
do
  key="$1"

  case $key in
      -i|--image-namespace)
      IMAGE_NAMESPACE="$2"
      shift # past argument
      ;;
      *)
        # unknown option
        echo "Unknown option"
        exit 1
      ;;
  esac
  shift # past argument or value
done

${method} ${app_name}
