apiVersion: v1
kind: Template
labels:
  template: openshift-playbooks
metadata:
  annotations:
    description: OpenShift Playbooks Deployment and Runtime Components
    iconClass: icon-ruby
    tags: ruby,jekyll
  name: "${APPLICATION_NAME}"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    replicas: 1
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
          deploymentconfig: "${APPLICATION_NAME}"
      spec:
        containers:
        - image: "${APPLICATION_NAME}:latest"
          name: "${APPLICATION_NAME}"
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APPLICATION_NAME}:latest"
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: 4000-tcp
      port: 4000
      protocol: TCP
      targetPort: 4000
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: openshift-playbooks
      template: openshift-playbooks
    name: openshift-playbooks
  spec:
    host: ""
    port:
      targetPort: 4000-tcp
    to:
      kind: ""
      name: openshift-playbooks
      weight: null
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: openshift-playbooks
