apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ping
spec:
  clusterIP: None
  ports:
    - name: ping
      port: 8888
  publishNotReadyAddresses: true
  selector:
    deploymentConfig: {{ .Release.Name }}