apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: motepair-server
  name: motepair-server
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: motepair-server:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/motepair/motepair-server.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
