apiVersion: v1
kind: Template
labels:
  template: play-framework-quickstart-rhel
metadata:
  annotations:
    description: Play Framework builder and sample application
    iconClass: icon-play
    tags: play,java
  name: play-framework-quickstart-rhel
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ${PLAY_BUILDER_NAME}
    name: rhel7-atomic
  spec:
    dockerImageRepository: registry.access.redhat.com/rhel7/rhel-atomic
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ${PLAY_BUILDER_NAME}
    name: ${PLAY_BUILDER_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${PLAY_APPLICATION_NAME}
    name: ${PLAY_APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${PLAY_BUILDER_NAME}
    name: ${PLAY_BUILDER_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${PLAY_BUILDER_NAME}:latest
    source:
      contextDir: ${PLAY_BUILDER_CONTEXT_DIR}
      git:
        ref: ${PLAY_BUILDER_SOURCE_REPOSITORY_REF}
        uri: ${PLAY_BUILDER_SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy:
        dockerFilePath: Dockerfile
        from:
          kind: ImageStreamTag
          name: rhel7-atomic:7.7
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${PLAY_APPLICATION_NAME}
    name: ${PLAY_APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${PLAY_APPLICATION_NAME}:latest
    source:
      contextDir: ${PLAY_APPLICATION_CONTEXT_DIR}
      git:
        ref: ${PLAY_APPLICATION_SOURCE_REPOSITORY_REF}
        uri: ${PLAY_APPLICATION_SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${PLAY_BUILDER_NAME}:latest
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- description: The name for the Play Framework builder.
  displayName: Play builder name
  name: PLAY_BUILDER_NAME
  required: true
  value: s2i-play
- description: Git source URI for Play Framework builder
  displayName: Play builder source url
  name: PLAY_BUILDER_SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/redhat-cop/containers-quickstarts.git
- description: Play Framework builder source branch/tag reference.
  displayName: Play builder source branch/tag reference.
  name: PLAY_BUILDER_SOURCE_REPOSITORY_REF
  required: false
  value: master
- description: Path within Git project to build containing the Play Framework builder;
    empty for root project directory.
  displayName: Play builder context directory.
  name: PLAY_BUILDER_CONTEXT_DIR
  required: false
  value: build-s2i-play
- description: The name for the Play Framework application.
  displayName: Play application name
  name: PLAY_APPLICATION_NAME
  required: true
  value: play-app
- description: Git source URI for Play Framework application
  displayName: Play application source url
  name: PLAY_APPLICATION_SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/playframework/play-samples.git
- description: Play Framework application source branch/tag reference.
  displayName: Play application source branch/tag reference.
  name: PLAY_APPLICATION_SOURCE_REPOSITORY_REF
  required: false
  value: 2.7.x
- description: Path within Git project to build containing the Play Framework application;
    empty for root project directory.
  displayName: Play application context directory.
  name: PLAY_APPLICATION_CONTEXT_DIR
  required: false
  value: "play-java-ebean-example"
