apiVersion: v1
kind: Template
labels:
  template: erlang-app
metadata:
  annotations:
    description: Erlang Deployment and Runtime Components
    tags: erlang,rebar3
  name: "${APPLICATION_NAME}"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    replicas: 1
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
          deploymentconfig: "${APPLICATION_NAME}"
      spec:
        containers:
        - image: "${APPLICATION_NAME}:latest"
          name: "${APPLICATION_NAME}"
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APPLICATION_NAME}:latest"
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
      template: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    host: ""
    port:
      targetPort: 8080-tcp
    to:
      kind: ""
      name: "${APPLICATION_NAME}"
      weight: null
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: erlang-cowboy-rest
