---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Cert Manager Deployment to support Acme Certificates
  name: cert-utils-operator-template
labels:
  template: cert-utils-operator-template
objects:
  - kind: OperatorGroup
    apiVersion: operators.coreos.com/v1
    metadata:
      name: cert-utils
    spec:
      targetNamespaces:
        - ${NAMESPACE}
  - kind: Subscription
    apiVersion: operators.coreos.com/v1alpha1
    metadata:
      name: cert-utils-operator
    spec:
      channel: alpha
      installPlanApproval: Automatic
      name: cert-utils-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
parameters:
  - name: NAMESPACE
    value: cert-mgmt
