---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Cert Manager Deployment to support Acme Certificates
  name: cert-manager-template
labels:
  template: cert-manager-template
objects:
  - kind: ProjectRequest
    apiVersion: v1
    metadata:
      name: ${NAMESPACE}
    displayName: Cert-Manager Project
  - kind: OperatorGroup
    apiVersion: operators.coreos.com/v1
    metadata:
      name: cert-utils
    spec:
      targetNamespaces:
        - ${NAMESPACE}
  - kind: Subscription
    apiVersion: operators.coreos.com/v1alpha1
    metadata:
      name: cert-utils-operator
    spec:
      channel: alpha
      installPlanApproval: Automatic
      name: cert-utils-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
  - kind: Secret
    apiVersion: v1
    data:
      aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    metadata:
      name: aws-secret-access-key-secret
    type: Opaque
  - kind: ClusterIssuer
    apiVersion: cert-manager.io/v1alpha2
    metadata:
      name: "${NAME}-production"
    spec:
      acme:
        email: "${ACME_EMAIL}"
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: letsencrypt-account-private-key
        solvers:
          - selector:
              dnsZones:
                - "${DNS_DOMAIN}"
            dns01:
              route53:
                region: ${AWS_REGION}
                accessKeyID: ${AWS_ACCESS_KEY_ID}
                secretAccessKeySecretRef:
                  name: "aws-secret-access-key-secret"
                  key: "aws-secret-access-key"
  - kind: ConfigMap
    apiVersion: v1
    data:
      ca-bundle.crt: |
        -----BEGIN CERTIFICATE-----
        MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
        MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
        DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
        SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
        GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
        AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
        q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
        SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
        Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
        a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
        /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
        AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
        CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
        bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
        c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
        VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
        ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
        MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
        Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
        AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
        uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
        wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
        X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
        PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
        KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
        -----END CERTIFICATE-----
    metadata:
      name: letsencrypt-ca
parameters:
  - name: NAME
    description: Name of the Deployment
    value: letsencrypt
  - name: NAMESPACE
    value: cert-manager
  - name: DNS_DOMAIN
    description: The DNS domain whereas the certificates are to be created
    required: true
  - name: AWS_REGION
    value: us-east-1
    required: true
  - name: AWS_ACCESS_KEY_ID
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    required: true
  - name: ACME_EMAIL
    required: true
