---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Cert Manager Deployment to support Acme Certificates
  name: cert-manager-template
labels:
  template: cert-manager-template
objects:
  - kind: Secret
    apiVersion: v1
    data:
      aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    metadata:
      name: aws-secret-access-key-secret
    type: Opaque
  - kind: ClusterIssuer
    apiVersion: cert-manager.io/v1
    metadata:
      name: "${NAME}-production"
    spec:
      acme:
        email: "${ACME_EMAIL}"
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: letsencrypt-account-private-key
        solvers:
          - selector:
              dnsZones:
                - "${DNS_DOMAIN}"
            dns01:
              route53:
                region: ${AWS_REGION}
                accessKeyID: ${AWS_ACCESS_KEY_ID}
                hostedZoneID: ${AWS_HOSTED_ZONE_ID}
                secretAccessKeySecretRef:
                  name: "aws-secret-access-key-secret"
                  key: "aws-secret-access-key"
parameters:
  - name: NAME
    description: Name of the Deployment
    value: letsencrypt
  - name: NAMESPACE
    value: cert-mgmt
  - name: DNS_DOMAIN
    description: The DNS domain whereas the certificates are to be created
    required: true
  - name: AWS_REGION
    value: us-east-1
    required: true
  - name: AWS_ACCESS_KEY_ID
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    required: true
  - name: ACME_EMAIL
    required: true
  - name: AWS_HOSTED_ZONE_ID
    required: false
