---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: OCP v4 Certificate and Configuration to load the certs
  name: "${NAME}-certs"
labels:
  template: "${NAME}-certs"
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: letsencrypt-ca
      namespace: ${LE_CA_NAMESPACE}
    data:
      ca-bundle.crt: |
        -----BEGIN CERTIFICATE-----
        MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
        MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
        DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
        SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
        GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
        AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
        q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
        SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
        Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
        a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
        /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
        AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
        CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
        bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
        c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
        VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
        ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
        MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
        Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
        AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
        uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
        wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
        X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
        PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
        KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
        -----END CERTIFICATE-----
  - kind: Certificate
    apiVersion: cert-manager.io/v1alpha2
    metadata:
      name: "api-${NAME}-cert"
      namespace: ${API_CERT_NAMESPACE}
    spec:
      secretName: "api-${NAME}-cert"
      issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
      dnsNames:
        - "api.${DNS_DOMAIN}"
  - kind: Certificate
    apiVersion: cert-manager.io/v1alpha2
    metadata:
      name: ingress-${NAME}-cert
      namespace: ${INGRESS_CERT_NAMESPACE}
    spec:
      secretName: "ingress-${NAME}-cert"
      issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
      dnsNames:
        - "*.apps.${DNS_DOMAIN}"
  - kind: APIServer
    apiVersion: config.openshift.io/v1
    metadata:
      name: cluster
    spec:
      servingCerts:
        namedCertificates:
          - names:
              - "api.${DNS_DOMAIN}"
            servingCertificate:
              name: "api-${NAME}-cert"
  - kind: IngressController
    apiVersion: operator.openshift.io/v1
    metadata:
      name: default
      namespace: ${INGRESS_OPERATOR_NAMESPACE}
    spec:
      defaultCertificate:
        name: "ingress-${NAME}-cert"
  - kind: Proxy
    apiVersion: config.openshift.io/v1
    metadata:
      name: cluster
    spec:
      trustedCA:
        name: letsencrypt-ca
parameters:
  - name: NAME
    description: Name of the Deployment
    value: letsencrypt
  - name: DNS_DOMAIN
    description: The DNS domain to use for the certificate
    required: true
  - name: LE_CA_NAMESPACE
    description: The namespace used for LE CA
    value: openshift-config
  - name: LE_CA_NAMESPACE
    description: The namespace used for LE CA
    value: openshift-config
  - name: API_CERT_NAMESPACE
    description: The namespace used for the API Cert
    value: openshift-config
  - name: INGRESS_CERT_NAMESPACE
    description: The namespace used for the Ingress Cert
    value: openshift-ingress
  - name: INGRESS_OPERATOR_NAMESPACE
    description: The namespace used for the Ingress Operator
    value: openshift-ingress-operator
