---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: OCP v4 Certificate and Configuration to load the certs
  name: "${NAME}-certs"
labels:
  template: "${NAME}-certs"
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: letsencrypt-ca
      namespace: ${LE_CA_NAMESPACE}
    data:
      ca-bundle.crt: |
        -----BEGIN CERTIFICATE-----
        MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
        TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
        cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
        WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
        RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
        AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
        R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
        sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
        NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
        Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
        /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
        AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
        Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
        FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
        AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
        Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
        gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
        PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
        ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
        CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
        lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
        avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
        yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
        yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
        hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
        HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
        MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
        nLRbwHOoq7hHwg==
        -----END CERTIFICATE-----
  - kind: Certificate
    apiVersion: cert-manager.io/v1alpha2
    metadata:
      name: "api-${NAME}-cert"
      namespace: ${API_CERT_NAMESPACE}
    spec:
      secretName: "api-${NAME}-cert"
      issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
      dnsNames:
        - "api.${DNS_DOMAIN}"
  - kind: Certificate
    apiVersion: cert-manager.io/v1alpha2
    metadata:
      name: ingress-${NAME}-cert
      namespace: ${INGRESS_CERT_NAMESPACE}
    spec:
      secretName: "ingress-${NAME}-cert"
      issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
      dnsNames:
        - "*.apps.${DNS_DOMAIN}"
  - kind: APIServer
    apiVersion: config.openshift.io/v1
    metadata:
      name: cluster
    spec:
      servingCerts:
        namedCertificates:
          - names:
              - "api.${DNS_DOMAIN}"
            servingCertificate:
              name: "api-${NAME}-cert"
  - kind: IngressController
    apiVersion: operator.openshift.io/v1
    metadata:
      name: default
      namespace: ${INGRESS_OPERATOR_NAMESPACE}
    spec:
      defaultCertificate:
        name: "ingress-${NAME}-cert"
  - kind: Proxy
    apiVersion: config.openshift.io/v1
    metadata:
      name: cluster
    spec:
      trustedCA:
        name: letsencrypt-ca
parameters:
  - name: NAME
    description: Name of the Deployment
    value: letsencrypt
  - name: DNS_DOMAIN
    description: The DNS domain to use for the certificate
    required: true
  - name: LE_CA_NAMESPACE
    description: The namespace used for LE CA
    value: openshift-config
  - name: LE_CA_NAMESPACE
    description: The namespace used for LE CA
    value: openshift-config
  - name: API_CERT_NAMESPACE
    description: The namespace used for the API Cert
    value: openshift-config
  - name: INGRESS_CERT_NAMESPACE
    description: The namespace used for the Ingress Cert
    value: openshift-ingress
  - name: INGRESS_OPERATOR_NAMESPACE
    description: The namespace used for the Ingress Operator
    value: openshift-ingress-operator
