---
namespace: jenkins-slaves

slave_repo_ref: v1.3

openshift_cluster_content:
- object: Environment Setup
  content:
  - name: Create Projects
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params_from_vars:
      NAMESPACE: "{{ namespace }}"
      NAMESPACE_DISPLAY_NAME: "{{ namespace }}"
    tags:
      - project
- object: jenkins-slave-nodes
  content:
  - name: jenkins-slave-ansible
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.yml"
    params: "{{ inventory_dir }}/../.openshift/params/ansible"
    params_from_vars:
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
    namespace: "{{ namespace }}"
    tags:
      - jenkins-slaves
      - ansible-slave
  - name: jenkins-slave-arachni
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.yml"
    params: "{{ inventory_dir }}/../.openshift/params/arachni"
    params_from_vars:
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
    namespace: "{{ namespace }}"
    tags:
      - jenkins-slaves
      - arachni-slave
  - name: jenkins-slave-golang
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.yml"
    params: "{{ inventory_dir }}/../.openshift/params/golang"
    params_from_vars:
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
    namespace: "{{ namespace }}"
    tags:
      - jenkins-slaves
      - golang-slave
  - name: jenkins-slave-gradle
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.yml"
    params: "{{ inventory_dir }}/../.openshift/params/gradle"
    params_from_vars:
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
    namespace: "{{ namespace }}"
    tags:
      - jenkins-slaves
      - gradle-slave
  - name: jenkins-slave-mongodb
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.yml"
    params: "{{ inventory_dir }}/../.openshift/params/mongodb"
    params_from_vars:
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
    namespace: "{{ namespace }}"
    tags:
      - jenkins-slaves
      - mongodb-slave
  - name: jenkins-slave-mvn
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.yml"
    params: "{{ inventory_dir }}/../.openshift/params/mvn"
    params_from_vars:
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
    namespace: "{{ namespace }}"
    tags:
    - jenkins-slaves
    - mvn-slave
  - name: jenkins-slave-npm
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.yml"
    params: "{{ inventory_dir }}/../.openshift/params/npm"
    params_from_vars:
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
    namespace: "{{ namespace }}"
    tags:
    - jenkins-slaves
    - npm-slave
  - name: jenkins-slave-python
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.yml"
    params: "{{ inventory_dir }}/../.openshift/params/python"
    params_from_vars:
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
    namespace: "{{ namespace }}"
    tags:
      - jenkins-slaves
      - python-slave
  - name: jenkins-slave-zap
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.yml"
    params: "{{ inventory_dir }}/../.openshift/params/zap"
    params_from_vars:
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
    namespace: "{{ namespace }}"
    tags:
    - jenkins-slaves
    - zap-slave
