kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: us-east-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    kubernetes.io/description: Storage provisioner for east datacenter EBS
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1a
  iopsPerGB: "10"
  encrypted: "false"
