---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Example python-kopf-s2i build
  name: openshift-template-deployer-build

parameters:
- name: FROM_IMAGE
  value: quay.io/redhat-cop/python-kopf-s2i:latest
- name: GIT_REPO
  value: https://github.com/redhat-cop/containers-quickstarts.git
- name: NAME
  value: openshift-template-deployer

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: master
      contextDir: build-s2i-python-kopf/examples/openshift-template-deployer
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: ${FROM_IMAGE}
        forcePull: true
    triggers: []
