---
apiVersion: v1
kind: Template
labels:
  template: ubi8-git
metadata:
  annotations:
    description: Git utility image
    tags: git, ubi8
  name: ubi8-git
objects:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "ubi8-git"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "ubi8-git:latest"
    source:
      contextDir: "${CONTEXT_DIR}"
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
    resources:
      requests: 
        cpu: 1
        memory: "512Mi"
      limits:
        cpu: 2
        memory: "1Gi"
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ubi8-git
  spec:
    lookupPolicy:
      local: true
parameters:
- description: Path within Git repository to build; empty for root of repository
  name: CONTEXT_DIR
  value: gitlab-runners/ubi8-git
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Git source URL for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/redhat-cop/containers-quickstarts
