apiVersion: v1
kind: Service
metadata:
  name: motepair-server
spec:
  clusterIP: ""
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: motepair-server
  sessionAffinity: None
  type: ClusterIP
status: {}
