openshift_cluster_content:
- object: projects
  content:
  - name: "create environments"
    file: "{{ inventory_dir }}/../projects/projects.yml"
    file_action: create
- object: builds
  content:
  - name: build play
    template: "{{ inventory_dir }}/../templates/build.yml"
    params: "{{ inventory_dir }}/../params/build"
    namespace: play-demo
- object: deployments
  content:
  - name: deploy MongoDB config servers
    template: "{{ inventory_dir }}/../templates/deployment.yml"
    params: "{{ inventory_dir }}/../params/deployment"
    namespace: play-demo
