apiVersion: v1
kind: Template
labels:
  template: openshift-playbooks-builder
metadata:
  annotations:
    description: OpenShift Playbooks s2i Build Components
    iconClass: icon-ruby
    tags: ruby, jekyll
  name: "${APPLICATION_NAME}"
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}:latest"
    postCommit: {}
    resources: {}
    source:
      contextDir: "${CONTEXT_DIR}"
      git:
        ref: "${SOURCE_REPOSITORY_REF}"
        uri: "${SOURCE_REPOSITORY_URL}"
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "${FROM_STREAM_TAG}"
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: openshift-playbooks
- description: Path within Git repository to build; empty for root of repository
  name: CONTEXT_DIR
  value: ""
- description: Image stream tag for the image you'd like to use to build the application
  name: FROM_STREAM_TAG
  required: true
  value: jekyll-builder:latest
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Git source URL for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/redhat-cop/openshift-playbooks
