#!/bin/sh

PLAY_ARCHIVE=$(ls -1 /deployments/*.tgz)

tar -vxzf ${PLAY_ARCHIVE} --strip 1 -C /deployments

PLAY_EXEC=$(find /deployments/bin/ -type f ! -name "*.*")

if [ -f /deployments/conf/application.conf ]; then
  echo '# https://playframework.com/documentation/2.6.x/AllowedHostsFilter#enabling-the-allowed-hosts-filter' >> /deployments/conf/application.conf
  echo 'play.filters.hosts.allowed = ["."]' >> /deployments/conf/application.conf
fi

if [ ! -z "${APPLICATION_SECRET}" ]; then
    APPLICATION_SECRET_PARAM="-Dplay.crypto.secret=${APPLICATION_SECRET}"
fi

eval ${PLAY_EXEC} ${APPLICATION_SECRET_PARAM} -Dhttp.port=8080 ${JAVA_OPTS_EXT}
