---
name: build-docker-generic-pr
on:
  pull_request:
    paths:
      - build-docker-generic/**
      - .github/workflows/build-docker-generic-pr.yaml
jobs:
  build:
    env:
      context: build-docker-generic
      image_name: build-docker-generic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Dockerfile
          image: ${{ env.image_name }}
          oci: true
          tags: "latest"
