---
name: github-runner-ubi8-pr
on:
  pull_request:
    paths:
      - github-runner-ubi8/**
      - .github/workflows/github-runner-ubi8-pr.yaml
jobs:
  build:
    env:
      CONTEXT_DIR: github-runner-ubi8
      IMAGE_NAME: github-runner-ubi8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check and verify version.json
        id: check_version
        uses: redhat-cop/github-actions/get-image-version@master
        with:
          IMAGE_CONTEXT_DIR: ${{ env.CONTEXT_DIR }}

      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.CONTEXT_DIR }}
          dockerfiles: |
            ./${{ env.CONTEXT_DIR }}/Dockerfile
          image: ${{ env.IMAGE_NAME }}
          oci: true
          tags: "${{ steps.check_version.outputs.IMAGE_TAGS }}"

      - name: Test image
        run: |
          echo "Running: podman run --entrypoint bash ${{ env.IMAGE_NAME }}:${{ steps.check_version.outputs.VERSION }} -c \"/home/github/bin/Runner.Listener --help\""
          podman run --entrypoint bash ${{ env.IMAGE_NAME }}:${{ steps.check_version.outputs.VERSION }} -c "/home/github/bin/Runner.Listener --help"
