name: gitlab-runners-ubi7-gitlab-runner-pr
on:
  pull_request:
    paths:
      - gitlab-runners/ubi7-gitlab-runner/**
jobs:
  build:
    env:
      context: gitlab-runners/ubi7-gitlab-runner
      image_name: gitlab-runners-ubi7-gitlab-runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check and verify version.json
        id: check_version
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          echo $(jq -r '.version' ${context}/version.json)
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          path: ${{ env.context }}
          push: false
          repository: ${{ env.image_name }}
          tags: ${{ steps.check_version.outputs.IMAGE_TAGS }}
      - name: Test image
        run: |
          echo "Running: docker run --entrypoint '/bin/sh' ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} -c 'wget --version'"
          docker run --entrypoint '/bin/sh' ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} -c 'wget --version'
          echo "Running: docker run --entrypoint '/bin/sh' ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} -c 'gitlab-runner --version'"
          docker run --entrypoint '/bin/sh' ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} -c 'gitlab-runner --version'
