---
name: hoverfly-pr
on:
  pull_request:
    paths:
      - hoverfly/**
      - .github/workflows/hoverfly-pr.yaml
jobs:
  build:
    env:
      context: hoverfly
      image_name: hoverfly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Dockerfile
          image: ${{ env.image_name }}
          oci: true
          tags: "latest"
