---
name: jenkins-agent-erlang-pr
on:
  pull_request:
    paths:
      - jenkins-agents/jenkins-agent-erlang/**
      - .github/workflows/jenkins-agent-erlang-pr.yaml

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    env:
      context: jenkins-agents/jenkins-agent-erlang
      image_name: jenkins-agent-erlang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ${{ env.context }}/Dockerfile

      - name: Log into ghcr.io
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Dockerfile
          image: ${{ env.image_name }}
          oci: true
          tags: "latest"

      - name: Test image
        run: |
          echo "Testing ${{ env.image_name }}"
          ./_test/kind/setup.sh ${{ env.image_name }}
