---
name: jenkins-agent-zap-pr
on:
  pull_request:
    paths:
      - jenkins-agents/jenkins-agent-zap/**
      - .github/workflows/jenkins-agent-zap-pr.yaml

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    env:
      context: jenkins-agents/jenkins-agent-zap
      image_name: jenkins-agent-zap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Build image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Dockerfile
          image: ${{ env.image_name }}
          oci: true
          tags: "latest"

      - name: Test image
        run: |
          echo "Testing ${{ env.image_name }}"
          ./_test/kind/setup.sh ${{ env.image_name }}
