---
name: jenkins-agent-arachni-pr
on:
  pull_request:
    paths:
      - jenkins-agents/jenkins-agent-arachni/**
      - .github/workflows/jenkins-agent-arachni-pr.yaml

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    env:
      context: jenkins-agents/jenkins-agent-arachni
      image_name: jenkins-agent-arachni
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Build image
        uses: redhat-actions/buildah-build@b4dc19b4ba891854660ab1f88a097d45aa158f76 # v2
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Dockerfile
          image: ${{ env.image_name }}
          oci: true
          tags: "latest"

      - name: Test image
        run: |
          echo "Testing ${{ env.image_name }}"
          ./_test/kind/setup.sh ${{ env.image_name }}
