apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: project.openshift.io/v1
  kind: ProjectRequest
  metadata:
    name: ${NAMESPACE}
    creationTimestam: null
  displayName: ${DISPLAY_NAME}
parameters:
  - name: NAMESPACE
  - name: DISPLAY_NAME
